### ISSUE TITLE
Add attach to header method

### ISSUE THREAD

**Issue by e-koch** [radio-astro-tools/radio_beam#17]
Input a header and add/update the beam properties of it.

**Comment by keflavich** [comment]
Yeah... apparently we're not dumping the BMAJ info back to the headers in spectral_cube now.  We need to fix that!

**Comment by e-koch** [comment]
Since radio_beam is optional for spectral-cube, I guess we need a fix in both?

**Comment by keflavich** [comment]
no, radio-beam is quasi-optional in spectral-cube, but there should be no expectation of getting beam information there without having it installed
