### ISSUE TITLE
Radio Beam is broken: cannot access functions within astropy

### ISSUE THREAD

**Issue by jpinedaf** [radio-astro-tools/radio_beam#26]
something is wrong with the integration of `astropy` and `radio-beam`, with `astropy` 1.0.4 or higher I get the following error message:
```
from radio_beam import beam
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1036d7bad96d> in <module>()
----> 1 from radio_beam import beam

/Users/jpineda/code/radio_beam/radio_beam/__init__.py in <module>()
      1 from .version import __version__
----> 2 from .beam import Beam, EllipticalGaussian2DKernel, EllipticalTophat2DKernel

/Users/jpineda/code/radio_beam/radio_beam/beam.py in <module>()
     10 # Imports for the custom kernels
     11 from astropy.modeling.models import Ellipse2D, Gaussian2D
---> 12 from astropy.modeling.utils import ellipse_extent
     13 from astropy.convolution import Kernel2D
     14 from astropy.convolution.kernels import _round_up_to_odd_integer

ImportError: cannot import name ellipse_extent
```
This is coming from https://github.com/radio-astro-tools/radio_beam/blob/master/radio_beam/beam.py#L12

I can reproduce the issue on Linux and MacOSX. The linux machine is managed using conda,.

**Comment by jpinedaf** [comment]
I guess this is related to #24 @keflavich @e-koch

**Comment by e-koch** [comment]
@jpinedaf, @keflavich  - Ah, ```ellipse_extent``` is a fairly recent addition and not part of the most recent astropy release -- https://github.com/astropy/astropy/commit/f8f45e074a634e28df8e10cce93df5938ebf3901.

It seems easiest just to make a local version of it in ```radio_beam```, at least until it's included in the next astropy release.

**Comment by keflavich** [comment]
@e-koch or just `try` to import it within the function that needs it, and raise a `NotImplementedError` if it can't be imported

**Comment by e-koch** [comment]
@keflavich - Alright. It only affects the kernels.

**Comment by jpinedaf** [comment]
fixed! Thanks
