### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/radio_beam#44]
@e-koch @low-sky We have a request to release an official version.  I think it's time.  What do we need to complete before then?  Please add to the checklist below:

 * [x] Finish the README
 * [x] Finish testing suite (see below)

**Comment by e-koch** [comment]
Most of these should be simple and easy to add.

Tests to add:

* [ ] `attach_to_header`
* [ ] `convolve`
* [ ] `deconvolve`
* [ ] `beam_projected_area`
* [ ] `jtok`
* [ ] `jtok_equiv`

**Comment by keflavich** [comment]
#47 is the other checkmark.

**Comment by keflavich** [comment]
With some basic docs in place, and the tests @e-koch added, I'm ready to make a v0.1 release.  Any objections, or is there anything critical to add?

**Comment by e-koch** [comment]
We still need a license (#50). I can't think of any other critical things.
